(ns hive-deepseek.dsh-launch
  "The cljw half of `dsh/hive-dsh`: boot DeepSeek Harness on every provider
   the hive swarm uses.

   cljw starts in tens of milliseconds but cannot spawn a process, so the work
   is split. This namespace reads hive-mcp's config, projects it to dsh routes
   (hive-deepseek.providers), probes keys and writes the patch. The shell
   wrapper only runs `pass show` for the entries `refs` names and execs the
   argv `launch` prints. Keys reach this process through its environment and
   are never printed, logged or written.

     cljw -cp src:script -m hive-deepseek.dsh-launch <command> [options]

   Commands:
     refs     one `pass <ENV> <entry>` line per keyed provider
     dump     the patch that would be written (no keys needed)
     check    probe each keyed provider whose key is in the environment
     launch   probe, write the patch, print the dsh argv one arg per line

   Options:
     --profile NAME      dsh profile (default hive)
     --config PATH       hive-mcp config.edn (default ~/.config/hive-mcp/config.edn)
     --only a,b          keep only these providers
     --default P/MODEL   agent default model, e.g. venice/deepseek-v4-flash
     --bridge URL        also point the hive-vessel plugin at URL
     --no-verify         launch without probing; by default a provider that
                         rejects its key (401/403) is left out of the patch
     -- ARGS             passed to the dsh app

   SPDX-License-Identifier: MIT"
  (:require [clojure.edn :as edn]
            [clojure.java.io :as io]
            [clojure.string :as str]
            [hive-deepseek.providers :as p]
            #?(:cljw [cljw.http.client :as http])))

(def auth-probe
  "Path under a provider's baseURL that answers 200 only to a valid key.
   `/models` is the fallback, but some providers serve it unauthenticated,
   and there a 200 proves nothing."
  {"openrouter" "/key"
   "venice" "/api_keys/rate_limits"})

(defn parse-args
  "Options map of ARGS: :command first, flags after, app args after `--`."
  [[command & args]]
  (loop [opts {:command command :profile "hive" :app-args []}
         [a & more :as args] args]
    (cond
      (empty? args) opts
      (= "--" a) (assoc opts :app-args (vec more))
      (= "--no-verify" a) (recur (assoc opts :no-verify true) more)
      (#{"--profile" "--config" "--only" "--default" "--bridge"} a)
      (recur (assoc opts (keyword (subs a 2)) (first more)) (rest more))
      :else (recur (update opts :app-args conj a) more))))

(defn- home [] (System/getenv "HOME"))

(defn- expand [path]
  (if (str/starts-with? path "~/") (str (home) (subs path 1)) path))

(defn read-config [path]
  (let [f (expand (or path "~/.config/hive-mcp/config.edn"))]
    (when-not (.exists (io/file f))
      (throw (ex-info (str "hive-mcp config not found: " f) {})))
    (edn/read-string {:default (fn [_tag v] v)} (slurp f))))

(defn- env-names
  "The variables among ROUTES' key variables that hold a non-blank value."
  [routes]
  (into #{}
        (keep (fn [{:keys [apiKeyEnv]}]
                (when (and apiKeyEnv (not (str/blank? (System/getenv apiKeyEnv))))
                  apiKeyEnv)))
        routes))

(defn- probe
  "HTTP status of ROUTE's authenticated probe, or an \"error ...\" string."
  [{:keys [provider baseURL apiKeyEnv]}]
  (try
    #?(:cljw (:status (http/get (str baseURL (get auth-probe provider "/models"))
                                {:headers {"Authorization" (str "Bearer " (System/getenv apiKeyEnv))}}))
       :default (throw (ex-info "probing needs cljw.http.client" {})))
    (catch #?(:cljw Exception :default Throwable) e
      (str "error " (ex-message e)))))

(defn- note [& xs]
  (binding [*out* *err*] (apply println xs)))

(defn- verified
  "ROUTES without the keyed ones whose provider rejects the key. A network
   error keeps the route: it says nothing about the key."
  [routes]
  (filterv (fn [{:keys [provider apiKeyEnv] :as r}]
             (or (nil? apiKeyEnv)
                 (let [status (probe r)]
                   (if (contains? #{401 403} status)
                     (do (note "skip" provider "key rejected" status) false)
                     true))))
           routes))

(defn- patch-text [routes {:keys [default bridge]}]
  (str "# Generated by hive-deepseek dsh/hive-dsh from hive-mcp :llm-providers.\n"
       "# Keys are credential references resolved from dsh's environment.\n"
       (p/->yaml (p/patch routes {:default default :bridge-url bridge}))
       "\n"))

(defn- profile-dir [profile]
  (str (or (System/getenv "DSH_HOME") (str (home) "/.dsh")) "/profiles/" profile))

(defn- report [served]
  (note "providers:" (str/join ", " (map :provider served))))

(defn -main [& args]
  (let [{:keys [command profile config only no-verify app-args] :as opts} (parse-args args)
        cfg (read-config config)
        all (p/routes (:llm-providers cfg) (some-> only (str/split #",")))
        {:keys [refs unresolved]} (p/credential-refs all (:secrets cfg))]
    (case command
      "refs"
      (do (doseq [{:keys [provider reason]} unresolved]
            (note "skip" provider (name reason)))
          (doseq [[env entry] (sort refs)]
            (println "pass" env entry)))

      "dump"
      (let [served (p/usable all (set (keys refs)))]
        (report served)
        (print (patch-text served opts))
        (flush))

      "check"
      (doseq [{:keys [provider] :as r} (p/usable all (env-names all))
              :when (:apiKeyEnv r)]
        (println (format "%-14s %s" provider (probe r))))

      "launch"
      (let [held (p/usable all (env-names all))
            served (if no-verify held (verified held))
            dir (profile-dir profile)
            file (str dir "/hive-providers.patch.yml")]
        (report served)
        (when (empty? served)
          (note "no provider could be served")
          (System/exit 1))
        (.mkdirs (io/file dir))
        (spit file (patch-text served opts))
        (doseq [arg (into [(or (System/getenv "DSH_BIN") "dsh") "--profile" profile "--patch" file]
                          app-args)]
          (println arg)))

      (do (note "usage: hive-dsh [--dump|--check] [options] [-- dsh app args]")
          (System/exit 2)))))
